package Modelo;
// Generated Feb 27, 2018 4:37:28 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Area generated by hbm2java
 */
public class Area  implements java.io.Serializable {


     private int claveArea;
     private String nombre;
     private Character statuo;
     private Set<Departamento> departamentos = new HashSet<Departamento>(0);

    public Area() {
    }

	
    public Area(int claveArea) {
        this.claveArea = claveArea;
    }
    public Area(int claveArea, String nombre, Character statuo, Set<Departamento> departamentos) {
       this.claveArea = claveArea;
       this.nombre = nombre;
       this.statuo = statuo;
       this.departamentos = departamentos;
    }
   
    public int getClaveArea() {
        return this.claveArea;
    }
    
    public void setClaveArea(int claveArea) {
        this.claveArea = claveArea;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Character getStatuo() {
        return this.statuo;
    }
    
    public void setStatuo(Character statuo) {
        this.statuo = statuo;
    }
    public Set<Departamento> getDepartamentos() {
        return this.departamentos;
    }
    
    public void setDepartamentos(Set<Departamento> departamentos) {
        this.departamentos = departamentos;
    }




}


