package Modelo;
// Generated Feb 27, 2018 4:37:28 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Departamento generated by hbm2java
 */
public class Departamento  implements java.io.Serializable {


     private int claveDepartamento;
     private Area area;
     private String nombre;
     private Character statuo;
     private Set<Movimiento> movimientos = new HashSet<Movimiento>(0);
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public Departamento() {
    }

	
    public Departamento(int claveDepartamento) {
        this.claveDepartamento = claveDepartamento;
    }
    public Departamento(int claveDepartamento, Area area, String nombre, Character statuo, Set<Movimiento> movimientos, Set<Usuario> usuarios) {
       this.claveDepartamento = claveDepartamento;
       this.area = area;
       this.nombre = nombre;
       this.statuo = statuo;
       this.movimientos = movimientos;
       this.usuarios = usuarios;
    }
   
    public int getClaveDepartamento() {
        return this.claveDepartamento;
    }
    
    public void setClaveDepartamento(int claveDepartamento) {
        this.claveDepartamento = claveDepartamento;
    }
    public Area getArea() {
        return this.area;
    }
    
    public void setArea(Area area) {
        this.area = area;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Character getStatuo() {
        return this.statuo;
    }
    
    public void setStatuo(Character statuo) {
        this.statuo = statuo;
    }
    public Set<Movimiento> getMovimientos() {
        return this.movimientos;
    }
    
    public void setMovimientos(Set<Movimiento> movimientos) {
        this.movimientos = movimientos;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }




}


