package Modelo;
// Generated Feb 27, 2018 4:37:28 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Movimiento generated by hbm2java
 */
public class Movimiento  implements java.io.Serializable {


     private int folio;
     private Departamento departamento;
     private Integer claveUsuario;
     private Integer claveProveedor;
     private Integer claveAutorizado;
     private String nombre;
     private String tipoMov;
     private String area;
     private String observaciones;
     private String fecha;
     private String procedencia;
     private String dirigido;
     private String asunto;
     private String tipo_transporte;
     private String tipo_usuario;

    public String getTipo_transporte() {
        return this.tipo_transporte;
    }

    public void setTipo_transporte(String tipo_transporte) {
        this.tipo_transporte = tipo_transporte;
    }

    public String getTipo_usuario() {
        return this.tipo_usuario;
    }

    public void setTipo_usuario(String tipo_usuario) {
        this.tipo_usuario = tipo_usuario;
    }

    public String getAsunto() {
        return this.asunto;
    }

    public void setAsunto(String asunto) {
        this.asunto = asunto;
    }

    public String getDirigido() {
        return this.dirigido;
    }

    public void setDirigido(String dirigido) {
        this.dirigido = dirigido;
    }
    public String getProcedencia() {
        return this.procedencia;
    }

    public void setProcedencia(String procedencia) {
        this.procedencia = procedencia;
    }

    public Movimiento() {
    }

	
    public Movimiento(int folio) {
        this.folio = folio;
    }
    public Movimiento(int folio, Departamento departamento, Integer claveUsuario, Integer claveProveedor, Integer claveAutorizado, String nombre, String tipoMov, String area, String observaciones, String fecha) {
       this.folio = folio;
       this.departamento = departamento;
       this.claveUsuario = claveUsuario;
       this.claveProveedor = claveProveedor;
       this.claveAutorizado = claveAutorizado;
       this.nombre = nombre;
       this.tipoMov = tipoMov;
       this.area = area;
       this.observaciones = observaciones;
       this.fecha = fecha;
    }
   
    public int getFolio() {
        return this.folio;
    }
    
    public void setFolio(int folio) {
        this.folio = folio;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public Integer getClaveUsuario() {
        return this.claveUsuario;
    }
    
    public void setClaveUsuario(Integer claveUsuario) {
        this.claveUsuario = claveUsuario;
    }
    public Integer getClaveProveedor() {
        return this.claveProveedor;
    }
    
    public void setClaveProveedor(Integer claveProveedor) {
        this.claveProveedor = claveProveedor;
    }
    public Integer getClaveAutorizado() {
        return this.claveAutorizado;
    }
    
    public void setClaveAutorizado(Integer claveAutorizado) {
        this.claveAutorizado = claveAutorizado;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTipoMov() {
        return this.tipoMov;
    }
    
    public void setTipoMov(String tipoMov) {
        this.tipoMov = tipoMov;
    }
    public String getArea() {
        return this.area;
    }
    
    public void setArea(String area) {
        this.area = area;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }




}


