package Modelo;
// Generated Feb 27, 2018 4:37:28 PM by Hibernate Tools 4.3.1



/**
 * PAutorizado generated by hbm2java
 */
public class PAutorizado  implements java.io.Serializable {


     private int claveAutorizado;
     private Proveedor proveedor;
     private String nombre;
     private Character statuo;

    public PAutorizado() {
    }

	
    public PAutorizado(int claveAutorizado) {
        this.claveAutorizado = claveAutorizado;
    }
    public PAutorizado(int claveAutorizado, Proveedor proveedor, String nombre, Character statuo) {
       this.claveAutorizado = claveAutorizado;
       this.proveedor = proveedor;
       this.nombre = nombre;
       this.statuo = statuo;
    }
   
    public int getClaveAutorizado() {
        return this.claveAutorizado;
    }
    
    public void setClaveAutorizado(int claveAutorizado) {
        this.claveAutorizado = claveAutorizado;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Character getStatuo() {
        return this.statuo;
    }
    
    public void setStatuo(Character statuo) {
        this.statuo = statuo;
    }




}


