package Modelo;
// Generated Feb 27, 2018 4:37:28 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor  implements java.io.Serializable {


     private int claveProveedor;
     private String nombre;
     private Character statuo;
     private Set<PAutorizado> PAutorizados = new HashSet<PAutorizado>(0);

    public Proveedor() {
    }

	
    public Proveedor(int claveProveedor) {
        this.claveProveedor = claveProveedor;
    }
    public Proveedor(int claveProveedor, String nombre, Character statuo, Set<PAutorizado> PAutorizados) {
       this.claveProveedor = claveProveedor;
       this.nombre = nombre;
       this.statuo = statuo;
       this.PAutorizados = PAutorizados;
    }
   
    public int getClaveProveedor() {
        return this.claveProveedor;
    }
    
    public void setClaveProveedor(int claveProveedor) {
        this.claveProveedor = claveProveedor;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Character getStatuo() {
        return this.statuo;
    }
    
    public void setStatuo(Character statuo) {
        this.statuo = statuo;
    }
    public Set<PAutorizado> getPAutorizados() {
        return this.PAutorizados;
    }
    
    public void setPAutorizados(Set<PAutorizado> PAutorizados) {
        this.PAutorizados = PAutorizados;
    }




}


