package Modelo;
// Generated Feb 27, 2018 4:37:28 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoUsuario generated by hbm2java
 */
public class TipoUsuario  implements java.io.Serializable {


     private int claveTipo;
     private String nombre;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public TipoUsuario() {
    }

	
    public TipoUsuario(int claveTipo) {
        this.claveTipo = claveTipo;
    }
    public TipoUsuario(int claveTipo, String nombre, Set<Usuario> usuarios) {
       this.claveTipo = claveTipo;
       this.nombre = nombre;
       this.usuarios = usuarios;
    }
   
    public int getClaveTipo() {
        return this.claveTipo;
    }
    
    public void setClaveTipo(int claveTipo) {
        this.claveTipo = claveTipo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }




}


